### ISSUE TITLE
IPv6 Handling for `wan_ip` causing crash

### ISSUE THREAD

**Issue by cpressland** [AngellusMortis/pyunifiprotect#282]
When running app with a UniFI Console with IPv6 enabled WAN we get the following exception:

```
Traceback (most recent call last):
  File "/Users/cpressland/.local/share/virtualenvs/pyunifiprotect-V1bbUH0L/bin/unifi-protect", line 8, in <module>
    sys.exit(start())
             ^^^^^^^
  File "/Users/cpressland/pyunifiprotect/pyunifiprotect/__main__.py", line 18, in start
    app()
  File "/Users/cpressland/.local/share/virtualenvs/pyunifiprotect-V1bbUH0L/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/cpressland/.local/share/virtualenvs/pyunifiprotect-V1bbUH0L/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/.local/share/virtualenvs/pyunifiprotect-V1bbUH0L/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/.local/share/virtualenvs/pyunifiprotect-V1bbUH0L/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
           ^^^^^^
  File "/Users/cpressland/.local/share/virtualenvs/pyunifiprotect-V1bbUH0L/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/cpressland/.local/share/virtualenvs/pyunifiprotect-V1bbUH0L/lib/python3.11/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/Users/cpressland/.local/share/virtualenvs/pyunifiprotect-V1bbUH0L/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/.local/share/virtualenvs/pyunifiprotect-V1bbUH0L/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/.local/share/virtualenvs/pyunifiprotect-V1bbUH0L/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/pyunifiprotect/pyunifiprotect/cli/__init__.py", line 131, in main
    loop.run_until_complete(update())
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/cpressland/pyunifiprotect/pyunifiprotect/cli/__init__.py", line 127, in update
    protect._bootstrap = await protect.get_bootstrap()  # pylint: disable=protected-access
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/pyunifiprotect/pyunifiprotect/api.py", line 776, in get_bootstrap
    return Bootstrap.from_unifi_dict(**data, api=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/pyunifiprotect/pyunifiprotect/data/base.py", line 116, in from_unifi_dict
    data = cls.unifi_dict_to_dict(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/pyunifiprotect/pyunifiprotect/data/bootstrap.py", line 187, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/pyunifiprotect/pyunifiprotect/data/base.py", line 338, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj(data[key], unifi_objs[key], api)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/pyunifiprotect/pyunifiprotect/data/base.py", line 278, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/pyunifiprotect/pyunifiprotect/data/nvr.py", line 845, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/pyunifiprotect/pyunifiprotect/data/base.py", line 780, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/pyunifiprotect/pyunifiprotect/data/base.py", line 331, in unifi_dict_to_dict
    data[key] = convert_unifi_data(data[key], cls.__fields__[key])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cpressland/pyunifiprotect/pyunifiprotect/utils.py", line 205, in convert_unifi_data
    value = field.type_(value)
            ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ipaddress.py", line 1315, in __init__
    self._ip = self._ip_int_from_string(addr_str)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ipaddress.py", line 1202, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in '2001:<snipped>:3e9'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10d8550d0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x10d8bef90>, 713697.718996708)]']
connector: <aiohttp.connector.TCPConnector object at 0x10d855190>
```

**Comment by cpressland** [comment]
@AngellusMortis I've managed to dump my bootstrap by patching `pyunifiprotect/api.py` and having it write out the collected payload as json. Upon inspecting the payload I can confirm that `wan_ip` is the only IPv6 address in the entire file. I'm happy to share this with you but given the file contains various auth tokens and other sensitive data I'd rather not do it publicly. Either way, I'm fairly confident this patch will be enough to get the Home Assistant integration working again.

**Comment by cpressland** [comment]
@AngellusMortis as an FYI this went live in HA 2023.5.4 today and is indeed working. 🎉
