### ISSUE TITLE
[Early Access] Protect 2.9.16 includes breaking changes: pyunifiprotect.exceptions.DataDecodeError: No modelKey

### ISSUE THREAD

**Issue by Cisien** [AngellusMortis/pyunifiprotect#307]
This issue is absolutely due to running an Early Access build of Unifi Protect. I'm creating this issue to track the changes that are showing up in the EA version of Protect so they can get addressed for the eventual release. I plan on digging into this error and possibly creating a PR.

```
2023-09-06 07:59:44.687 WARNING (MainThread) [pyunifiprotect.utils] Unknown video mode: sport
2023-09-06 07:59:44.697 WARNING (MainThread) [pyunifiprotect.utils] Unknown video mode: slowShutter
2023-09-06 07:59:44.700 WARNING (MainThread) [pyunifiprotect.utils] Unknown video mode: sport
2023-09-06 07:59:44.701 WARNING (MainThread) [pyunifiprotect.utils] Unknown video mode: slowShutter
2023-09-06 07:59:44.702 WARNING (MainThread) [pyunifiprotect.utils] Unknown video mode: sport
2023-09-06 07:59:44.703 WARNING (MainThread) [pyunifiprotect.utils] Unknown video mode: slowShutter
2023-09-06 07:59:46.127 ERROR (MainThread) [homeassistant.components.unifiprotect] Error setting up UniFi Protect integration: No modelKey
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/unifiprotect/__init__.py", line 105, in async_setup_entry
await _async_setup_entry(hass, entry, data_service)
File "/usr/src/homeassistant/homeassistant/components/unifiprotect/__init__.py", line 137, in _async_setup_entry
await data_service.async_setup()
File "/usr/src/homeassistant/homeassistant/components/unifiprotect/data.py", line 114, in async_setup
await self.async_refresh()
File "/usr/src/homeassistant/homeassistant/components/unifiprotect/data.py", line 134, in async_refresh
updates = await self.api.update(force=force)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyunifiprotect/api.py", line 612, in update
events = await self.get_events(start=self._last_update_dt or max_event_dt, end=now_dt)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyunifiprotect/api.py", line 731, in get_events
event = create_from_unifi_dict(event_dict, api=self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyunifiprotect/data/convert.py", line 61, in create_from_unifi_dict
raise DataDecodeError("No modelKey")
pyunifiprotect.exceptions.DataDecodeError: No modelKey
2023-09-06 07:59:46.131 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Layer 1 - Dream Machine SE for unifiprotect
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/unifiprotect/__init__.py", line 105, in async_setup_entry
await _async_setup_entry(hass, entry, data_service)
File "/usr/src/homeassistant/homeassistant/components/unifiprotect/__init__.py", line 137, in _async_setup_entry
await data_service.async_setup()
File "/usr/src/homeassistant/homeassistant/components/unifiprotect/data.py", line 114, in async_setup
await self.async_refresh()
File "/usr/src/homeassistant/homeassistant/components/unifiprotect/data.py", line 134, in async_refresh
updates = await self.api.update(force=force)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyunifiprotect/api.py", line 612, in update
events = await self.get_events(start=self._last_update_dt or max_event_dt, end=now_dt)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyunifiprotect/api.py", line 731, in get_events
event = create_from_unifi_dict(event_dict, api=self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyunifiprotect/data/convert.py", line 61, in create_from_unifi_dict
raise DataDecodeError("No modelKey")
pyunifiprotect.exceptions.DataDecodeError: No modelKey
```

**Comment by cyberpower678** [comment]
Yep, just came here to report this.  Client is completely bricked with the newest Protect update.

**Comment by AngellusMortis** [comment]
Duplicate: https://github.com/AngellusMortis/pyunifiprotect/issues/307

Also, EA versions are not supported for HA. This is why. If you do not want HA to randomly break when UI releases a new version, do not use EA.

**Comment by cyberpower678** [comment]
@Cisien if you catch the exception and run the update method again, it will still connect.  It's a good work around until @AngellusMortis addresses the issue.

**Comment by bdraco** [comment]
Please don't ping maintainers. The bot already does this. Thanks
