### ISSUE TITLE
Authentication errors every 2h

### ISSUE THREAD

**Issue by jasperslits** [AngellusMortis/pyunifiprotect#320]
With the risk of this being closed / rejected asa it's not the right place. 

I am using:
Home Assistant 2023.11.0
Unifi protect 2.9.42
UDM PRO with UniFi OS 3.2.6 running on 192.168.178.1
pyunifiprotect 4.21.0 (manually updated to get rid of some HA warnings related to sport). 

I am seeing seeing "2023-11-20 18:18:47.292 ERROR (MainThread) [homeassistant.components.unifiprotect.data] Auth error while updating" every 2 hours in the logs since recently, I think since 2.9.4x

Upon turning debugging on for pyunifiprotect, the following logs are obtained. 

```
2023-11-20 18:18:00.960 DEBUG (MainThread) [pyunifiprotect.websocket] WS Timeout loop sleep 29.841506746946834
2023-11-20 18:18:02.260 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2023-11-20 18:18:07.261 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2023-11-20 18:18:12.262 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2023-11-20 18:18:17.262 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2023-11-20 18:18:22.262 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2023-11-20 18:18:27.264 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2023-11-20 18:18:30.802 DEBUG (MainThread) [pyunifiprotect.websocket] WS Timeout loop sleep 26.708600973011926
2023-11-20 18:18:32.265 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2023-11-20 18:18:37.265 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2023-11-20 18:18:42.266 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2023-11-20 18:18:47.267 DEBUG (MainThread) [pyunifiprotect.api] Request url: https://192.168.178.1/api/auth/login
2023-11-20 18:18:47.283 DEBUG (MainThread) [pyunifiprotect.api] 401 application/json <ClientResponse(https://192.168.178.1/api/auth/login) [401 Unauthorized]>
<CIMultiDictProxy('Server': 'nginx', 'Date': 'Mon, 20 Nov 2023 17:18:47 GMT', 'Content-Type': 'application/json', 'Content-Length': '47', 'Connection': 'keep-alive', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'Set-Cookie': 'TOKEN=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT; samesite=none; secure; httponly')>

2023-11-20 18:18:47.283 DEBUG (MainThread) [pyunifiprotect.api] Authenticated successfully!
2023-11-20 18:18:47.283 DEBUG (MainThread) [pyunifiprotect.api] Request url: https://192.168.178.1/proxy/protect/api/bootstrap
2023-11-20 18:18:47.292 ERROR (MainThread) [homeassistant.components.unifiprotect.data] Auth error while updating
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/unifiprotect/data.py", line 134, in async_refresh
    updates = await self.api.update(force=force)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyunifiprotect/api.py", line 600, in update
    self._bootstrap = await self.get_bootstrap()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyunifiprotect/api.py", line 763, in get_bootstrap
    data = await self.api_request_obj("bootstrap")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyunifiprotect/api.py", line 328, in api_request_obj
    data = await self.api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyunifiprotect/api.py", line 311, in api_request
    data = await self.api_request_raw(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyunifiprotect/api.py", line 286, in api_request_raw
    raise NotAuthorized(msg % (url, response.status, reason))
pyunifiprotect.exceptions.NotAuthorized: Request failed: /proxy/protect/api/bootstrap - Status: 401 - Reason: {'code': 401, 'message': 'Unauthorized'}
2023-11-20 18:18:52.269 DEBUG (MainThread) [pyunifiprotect.utils] Authentication token decode error: Not enough segments
2023-11-20 18:18:52.269 DEBUG (MainThread) [pyunifiprotect.api] Request url: https://192.168.178.1/api/auth/login
2023-11-20 18:18:52.653 DEBUG (MainThread) [pyunifiprotect.api] 200 application/json <ClientResponse(https://192.168.178.1/api/auth/login) [200 OK]>
<CIMultiDictProxy('Server': 'nginx', 'Date': 'Mon, 20 Nov 2023 17:18:52 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '3379', 'Connection': 'keep-alive', 'Set-Cookie': 'TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1N2E1MWZhYi05ZGJkLTRiOTEtOTA2NC01ZDNkMzNiODc1ZTQiLCJwYXNzd29yZFJldmlzaW9uIjoxNzAwMjk3Mzc5LCJpc1JlbWVtYmVyZWQiOmZhbHNlLCJjc3JmVG9rZW4iOiI0YzczOTU1Zi04MTU0LTRmZDgtOTY3Ny1jZWE2ODA1MDVlMWEiLCJpYXQiOjE3MDA1MDA3MzIsImV4cCI6MTcwMDUwNzkzMiwianRpIjoiNzY1NmJhMjUtNjJiYi00YTdmLWI2MjEtM2FlMTkxYjA3YjQyIn0.JeMTQndsZsxsiRMkE1ITTjGslFe7742CsDtb_2zzIIU; path=/; expires=Mon, 20 Nov 2023 19:18:52 GMT; samesite=none; secure; httponly', 'x-updated-csrf-token': '4c73955f-8154-4fd8-9677-cea680505e1a', 'x-token-expire-time': '1700507932470', 'X-Response-Time': '378ms', 'Access-Control-Allow-Credentials': 'false', 'Access-Control-Expose-Headers': 'Content-Disposition, Content-Range, Filename, Location, Range, Upload-Length, Upload-Offset, X-Connection-Type, X-Csrf-Token, X-File-Id, X-Token-Expire-Time, X-Updated-Csrf-Token', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-DNS-Prefetch-Control': 'off', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'X-Csrf-Token': '4c73955f-8154-4fd8-9677-cea680505e1a')>

2023-11-20 18:18:52.653 DEBUG (MainThread) [pyunifiprotect.api] Authenticated successfully!
2023-11-20 18:18:52.653 DEBUG (MainThread) [pyunifiprotect.api] Request url: https://192.168.178.1/proxy/protect/api/bootstrap
2023-11-20 18:18:52.700 DEBUG (MainThread) [pyunifiprotect.websocket] Disconnecting websocket...
2023-11-20 18:18:52.700 DEBUG (MainThread) [pyunifiprotect.websocket] Websocket disconnected
2023-11-20 18:18:52.700 DEBUG (MainThread) [pyunifiprotect.websocket] Adding subscription: <bound method ProtectApiClient._process_ws_message of <pyunifiprotect.api.ProtectApiClient object at 0x7f53dfd92f50>>
2023-11-20 18:18:52.700 DEBUG (MainThread) [pyunifiprotect.websocket] Scheduling WS connect...
2023-11-20 18:18:52.701 DEBUG (MainThread) [pyunifiprotect.websocket] Connecting WS to wss://192.168.178.1/proxy/protect/ws/updates?lastUpdateId=fd091387-c9ab-4b8d-83f3-5eeb91282f2e
2023-11-20 18:18:52.714 DEBUG (MainThread) [pyunifiprotect.websocket] Connected to Websocket successfully
2023-11-20 18:18:52.714 INFO (MainThread) [pyunifiprotect.api] Websocket re-connected successfully
```

The JWT from 2023-11-20 18:18:52.653 decodes to: 
```JSON
{
  "userId": "57a51fab-9dbd-4b91-9064-5d3d33b875e4",
  "passwordRevision": 1700297379,
  "isRemembered": false,
  "csrfToken": "4c73955f-8154-4fd8-9677-cea680505e1a",
  "iat": 1700500732,
  "exp": 1700507932,
  "jti": "7656ba25-62bb-4a7f-b621-3ae191b07b42"
}

```

Exp 1700507932 translates to Monday, 20 November 2023 20:18:52 [GMT+01:00] so that's exactly 2 hours from iat. 

I dont know if there's been a change in Unifi's login handling since UniFi OS 3.2.6 or with Protect but this always worked fine for a year+ when running beta versions. I haven't seen any other reports in Home Assistant's git repo but seeing it's coming from pyunifiprotect, I thought this is an appropriate place. 

As re-authentication takes place, it's just noise in the logs every 2hours and doesnt break anything (camera, doorbell notification).

**Comment by jasperslits** [comment]
Fixed with PR #330
