### ISSUE TITLE
AttributeError: 'URL' object has no attribute 'joinpath'

### ISSUE THREAD

**Issue by ep1cman** [AngellusMortis/pyunifiprotect#352]
Looks like d8f92dc has introduced an issue as reported here:

https://github.com/ep1cman/unifi-protect-backup/issues/130#issue-2140547788

```
2024-02-17 13:56:16 [  WARNING  ] unifi_protect_backup.unifi_protect_backup_core :  Failed to connect to UniFi Protect, retrying in 2s...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 190, in start
    await self._protect.update()
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 673, in update
    self._bootstrap = await self.get_bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 991, in get_bootstrap
    data = await self.api_request_obj("bootstrap")
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 379, in api_request_obj
    data = await self.api_request(
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 358, in api_request
    data = await self.api_request_raw(
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 319, in api_request_raw
    response = await self.request(
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 255, in request
    await self.ensure_authenticated()
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 416, in ensure_authenticated
    await self.authenticate()
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 441, in authenticate
    response = await self.request("post", url=url, json=auth)
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 257, in request
    request_url = self._url.joinpath(url[1:])
AttributeError: 'URL' object has no attribute 'joinpath'
```

**Comment by AngellusMortis** [comment]
Upgrade yarl.
